#!/bin/sh
set -e -u -x

cd "$(dirname "$0")"/linux
[ -e .config ] || ../virtme-ng/vng --config=../config --kconfig
../virtme-ng/vng --build

cd tools/perf
make -j"$(nproc)"

cd ../../../qemu
[ -e build/Makefile ] || ./configure --disable-docs --disable-tcg --enable-kvm
make -j"$(nproc)"

cd ../bpftrace
[ -e build/CMakeCache.txt ] || cmake -B build \
	-DCMAKE_BUILD_TYPE=Release \
	-DBUILD_TESTING=OFF \
	-DENABLE_MAN=OFF \
	-DENABLE_SKB_OUTPUT=OFF
make -C build -j"$(nproc)"
