#!/bin/sh
set -e -u -x
cd "$(dirname "$0")"/workdir
sudo mkdir -p tmpfs
while sudo umount ./tmpfs; do :; done
sudo mount -t tmpfs -o size=4G tmpfs tmpfs
cd tmpfs
dbench -t 4 "$(getconf _NPROCESSORS_ONLN)"
