#!/bin/sh
set -e -u -x
sudo apt-get update
sudo apt-get build-dep linux qemu
sudo apt-get install -y \
	clang \
	dbench \
	inotify-tools \
	libbabeltrace-dev \
	libcapstone-dev \
	libdebuginfod-dev \
	libpfm4-dev \
	linuxptp \
	llvm-dev \
	systemtap-sdt-dev
