#!/bin/sh
set -e -u -x
cd "$(dirname "$0")"/linux
export PATH=../qemu/build:"$PATH"
mkdir -p ../workdir
traced_pid=
traced_probes_pid=
perfetto_pid=
cleanup() {
	if [ -n "$perfetto_pid" ]; then
		kill "$perfetto_pid"
		wait "$perfetto_pid" || true
	fi
	if [ -n "$traced_probes_pid" ]; then
		sudo kill "$traced_probes_pid"
		wait "$traced_probes_pid" || true
	fi
	if [ -n "$traced_pid" ]; then
		kill "$traced_pid"
		wait "$traced_pid" || true
	fi
}
trap cleanup EXIT
tracebox=$(command -v tracebox)
traced_pid=$(../start-traced-host "$tracebox")
traced_probes_pid=$(sudo ../start-traced-probes-host "$tracebox")
perfetto_pid=$(../start-perfetto-host "$tracebox")
../virtme-ng/vng \
	--ssh=10002 \
	--cpus="$(($(getconf _NPROCESSORS_ONLN) * 2))" \
	--cwd=../workdir \
	--memory=8G \
	--name=kvm-slice-ctrl \
	--rwdir=../workdir \
	"$@"
chown "$(id -u):$(id -g)" ../workdir/perfetto.trace
