#!/bin/sh
set -e -u -x
cd "$(dirname "$0")"
mkdir -p workdir
rm -f workdir/traced_probes_host_ready
mkfifo workdir/traced_probes_host_ready
# shellcheck disable=SC2024
env \
	PERFETTO_PRODUCER_SOCK_NAME=workdir/producer_host.sock \
	TRACED_PROBES_NOTIFY_FD=3 \
	"$1" traced_probes \
	</dev/null >workdir/traced_probes_host.log 2>&1 3>workdir/traced_probes_host_ready &
pid=$!
if [ "$(dd if=workdir/traced_probes_host_ready bs=1 count=1)" != "1" ]; then
	exit 1
fi
echo "$pid"
