#!/bin/sh
set -e -u -x
cd "$(dirname "$0")"
stdbuf -i0 -o0 -e0 trace-cmd record \
	-b 600000 \
	-C tai \
	-e lock/lock_acquire \
	-e lock/lock_contended \
	-e lock/lock_acquired \
	-e lock/lock_release \
	-e msr/write_msr \
	-e sched/sched_process_exec \
	-o workdir/trace-guest.dat \
	--temp /tmp/ \
	</dev/null >workdir/trace_cmd_guest.log 2>&1 &
while ! grep --perl-regexp "\AHit Ctrl" workdir/trace_cmd_guest.log >/dev/null; do
	sleep 1
done
echo "$!"
