#!/bin/sh
set -e -u -x
cd "$(dirname "$0")"/linux
mkdir -p ../workdir
exec ../virtme-ng/vng \
	--ssh=10002 \
	--cpus="$(($(getconf _NPROCESSORS_ONLN) * 2))" \
	--cwd=../workdir \
	--memory=8G \
	--name=kvm-slice-ctrl \
	--rwdir=../workdir \
	--user="$USER" \
	"$@"
