#!/bin/sh
set -e -u -x
cd "$(dirname "$0")"/linux
mkdir -p ../workdir
export PATH=../qemu/build:"$PATH"
exec taskset --cpu-list 0-3 ../virtme-ng/vng \
	--cpus=8 \
	--cwd=../workdir \
	--memory=16G \
	--name=kvm-slice-ctrl \
	--ssh=10002 \
	--rwdir=../workdir \
	--user="$USER" \
	--verbose \
	"$@"
